config/routes.rb
Displode::Application.routes.draw do
  resources :followees

  match "profile" => "profile#index"

  resources :notifications

  resources :following

  resources :followers

  resources :posts

  root :to => "home#index"

end

app/models/notification.rb
class Notification < ActiveRecord::Base
  attr_accessible :action, :client, :entity, :object
end

app/controllers/notifications_controller.rb
class NotificationsController < ApplicationController
  # GET /notifications
  # GET /notifications.json
  def index
    @notifications = Notification.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @notifications }
    end
  end

  # GET /notifications/1
  # GET /notifications/1.json
  def show
    @notification = Notification.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @notification }
    end
  end

  # GET /notifications/new
  # GET /notifications/new.json
  def new
    @notification = Notification.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @notification }
    end
  end

  # GET /notifications/1/edit
  def edit
    @notification = Notification.find(params[:id])
  end

  # POST /notifications
  # POST /notifications.json
  def create
    @notification = Notification.new(params[:notification])

    respond_to do |format|
      if @notification.save
        format.html { redirect_to @notification, notice: 'Notification was successfully created.' }
        format.json { render json: @notification, status: :created, location: @notification }
      else
        format.html { render action: "new" }
        format.json { render json: @notification.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /notifications/1
  # PUT /notifications/1.json
  def update
    @notification = Notification.find(params[:id])

    respond_to do |format|
      if @notification.update_attributes(params[:notification])
        format.html { redirect_to @notification, notice: 'Notification was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @notification.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /notifications/1
  # DELETE /notifications/1.json
  def destroy
    @notification = Notification.find(params[:id])
    @notification.destroy

    respond_to do |format|
      format.html { redirect_to notifications_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/notifications_helper.rb
module NotificationsHelper
end

app/views/notifications/_form.html.slim
= form_for @notification, :html => { :class => "form-horizontal" } do |f|
  .control-group
    = f.label :entity, :class => 'control-label'
    .controls
      = f.text_field :entity, :class => 'text_field'
  .control-group
    = f.label :action, :class => 'control-label'
    .controls
      = f.text_field :action, :class => 'text_field'
  .control-group
    = f.label :object, :class => 'control-label'
    .controls
      = f.text_field :object, :class => 'text_field'
  .control-group
    = f.label :client, :class => 'control-label'
    .controls
      = f.text_field :client, :class => 'text_field'
  .form-actions
    = f.submit nil, :class => 'btn btn-primary'
    '
    = link_to t('.cancel', :default => t("helpers.links.cancel")), notifications_path, :class => 'btn'

app/views/notifications/edit.html.slim
- model_class = @notification.class
div class="page-header"
  h1=t '.title', :default => t('helpers.titles.edit', :model => model_class.model_name.human, :default => "Edit #{model_class.model_name.human}")
= render :partial => "form"

app/views/notifications/index.html.slim
- model_class = Notification.new.class
div class="page-header"
  h1=t '.title', :default => model_class.model_name.human.pluralize
table class="table table-striped"
  thead
    tr
      th= model_class.human_attribute_name(:id)
      th= model_class.human_attribute_name(:entity)
      th= model_class.human_attribute_name(:action)
      th= model_class.human_attribute_name(:object)
      th= model_class.human_attribute_name(:client)
      th= model_class.human_attribute_name(:created_at)
      th=t '.actions', :default => t("helpers.actions")
  tbody
    - @notifications.each do |notification|
      tr
        td= link_to notification.id, notification_path(notification)
        td= notification.entity
        td= notification.action
        td= notification.object
        td= notification.client
        td=l notification.created_at
        td
          = link_to t('.edit', :default => t("helpers.links.edit")), edit_notification_path(notification), :class => 'btn btn-mini'
          '
          = link_to t('.destroy', :default => t("helpers.links.destroy")), notification_path(notification), :method => :delete, :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')), :class => 'btn btn-mini btn-danger'

= link_to t('.new', :default => t("helpers.links.new")), new_notification_path, :class => 'btn btn-primary'

app/views/notifications/new.html.slim
- model_class = @notification.class
div class="page-header"
  h1=t '.title', :default => t('helpers.titles.new', :model => model_class.model_name.human, :default => "New #{model_class.model_name.human}")
= render :partial => "form"

app/views/notifications/show.html.slim
- model_class = @notification.class
div class="page-header"
  h1=t '.title', :default => model_class.model_name.human

p
  strong= model_class.human_attribute_name(:entity) + ':'
  br
  = @notification.entity
p
  strong= model_class.human_attribute_name(:action) + ':'
  br
  = @notification.action
p
  strong= model_class.human_attribute_name(:object) + ':'
  br
  = @notification.object
p
  strong= model_class.human_attribute_name(:client) + ':'
  br
  = @notification.client

.form-actions
  = link_to t('.back', :default => t("helpers.links.back")), notifications_path, :class => 'btn'
  '
  = link_to t('.edit', :default => t("helpers.links.edit")), edit_notification_path(@notification), :class => 'btn'
  '
  = link_to t('.destroy', :default => t("helpers.links.destroy")), notification_path(@notification), :method => "delete", :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')), :class => 'btn btn-danger'