config/routes.rb
Displode::Application.routes.draw do
  resources :followees

  match "profile" => "profile#index"

  resources :notifications

  resources :following

  resources :followers

  resources :posts

  root :to => "home#index"

end

app/models/followee.rb
class Followee < ActiveRecord::Base
  attr_accessible :avatar, :entity, :firstName, :handle, :lastName
end

app/controllers/followees_controller.rb
class FolloweesController < ApplicationController
  # GET /followees
  # GET /followees.json
  def index
    @followees = Followee.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @followees }
    end
  end

  # GET /followees/1
  # GET /followees/1.json
  def show
    @followee = Followee.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @followee }
    end
  end

  # GET /followees/new
  # GET /followees/new.json
  def new
    @followee = Followee.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @followee }
    end
  end

  # GET /followees/1/edit
  def edit
    @followee = Followee.find(params[:id])
  end

  # POST /followees
  # POST /followees.json
  def create
    @followee = Followee.new(params[:followee])

    respond_to do |format|
      if @followee.save
        format.html { redirect_to @followee, notice: 'Followee was successfully created.' }
        format.json { render json: @followee, status: :created, location: @followee }
      else
        format.html { render action: "new" }
        format.json { render json: @followee.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /followees/1
  # PUT /followees/1.json
  def update
    @followee = Followee.find(params[:id])

    respond_to do |format|
      if @followee.update_attributes(params[:followee])
        format.html { redirect_to @followee, notice: 'Followee was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @followee.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /followees/1
  # DELETE /followees/1.json
  def destroy
    @followee = Followee.find(params[:id])
    @followee.destroy

    respond_to do |format|
      format.html { redirect_to followees_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/followees_helper.rb
module FolloweesHelper
end

app/views/followees/_form.html.slim
= form_for @followee, :html => { :class => "form-horizontal" } do |f|
  .control-group
    = f.label :entity, :class => 'control-label'
    .controls
      = f.text_field :entity, :class => 'text_field'
  .control-group
    = f.label :handle, :class => 'control-label'
    .controls
      = f.text_field :handle, :class => 'text_field'
  .control-group
    = f.label :firstName, :class => 'control-label'
    .controls
      = f.text_field :firstName, :class => 'text_field'
  .control-group
    = f.label :lastName, :class => 'control-label'
    .controls
      = f.text_field :lastName, :class => 'text_field'
  .control-group
    = f.label :avatar, :class => 'control-label'
    .controls
      = f.text_field :avatar, :class => 'text_field'
  .form-actions
    = f.submit _('Follow'), :class => 'btn btn-primary'
    '
    = link_to _('Cancel'), followees_path, :class => 'btn'

app/views/followees/edit.html.slim
- model_class = @followee.class
div class="page-header"
  h1=_ "Edit #{model_class.model_name.human} Information"
= render :partial => "form"

app/views/followees/index.html.slim
- model_class = Followee.new.class
div class="page-header"
  h1=t '.title', :default => model_class.model_name.human.pluralize
table class="table table-striped"
  thead
    tr
      th= model_class.human_attribute_name(:id)
      th= model_class.human_attribute_name(:entity)
      th= model_class.human_attribute_name(:handle)
      th= model_class.human_attribute_name(:firstName)
      th= model_class.human_attribute_name(:lastName)
      th= model_class.human_attribute_name(:avatar)
      th= model_class.human_attribute_name(:created_at)
      th=t '.actions', :default => t("helpers.actions")
  tbody
    - @followees.each do |followee|
      tr
        td= link_to followee.id, followee_path(followee)
        td= followee.entity
        td= followee.handle
        td= followee.firstName
        td= followee.lastName
        td= followee.avatar
        td=l followee.created_at
        td
          = link_to t('.edit', :default => t("helpers.links.edit")), edit_followee_path(followee), :class => 'btn btn-mini'
          '
          = link_to t('.destroy', :default => t("helpers.links.destroy")), followee_path(followee), :method => :delete, :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')), :class => 'btn btn-mini btn-danger'

= link_to _('Follow External Link'), new_followee_path, :class => 'btn btn-primary'

app/views/followees/new.html.slim
- model_class = @followee.class
div class="page-header"
  h1=t '.title', :default => t('helpers.titles.new', :model => model_class.model_name.human, :default => "New #{model_class.model_name.human}")
= render :partial => "form"

app/views/followees/show.html.slim
- model_class = @followee.class
div class="page-header"
  h1=t '.title', :default => model_class.model_name.human

p
  strong= model_class.human_attribute_name(:entity) + ':'
  br
  = @followee.entity
p
  strong= model_class.human_attribute_name(:handle) + ':'
  br
  = @followee.handle
p
  strong= model_class.human_attribute_name(:firstName) + ':'
  br
  = @followee.firstName
p
  strong= model_class.human_attribute_name(:lastName) + ':'
  br
  = @followee.lastName
p
  strong= model_class.human_attribute_name(:avatar) + ':'
  br
  = @followee.avatar

.form-actions
  = link_to t('.back', :default => t("helpers.links.back")), followees_path, :class => 'btn'
  '
  = link_to t('.edit', :default => t("helpers.links.edit")), edit_followee_path(@followee), :class => 'btn'
  '
  = link_to t('.destroy', :default => t("helpers.links.destroy")), followee_path(@followee), :method => "delete", :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')), :class => 'btn btn-danger'