config/routes.rb
Displode::Application.routes.draw do
  resources :followees

  match "profile" => "profile#index"

  resources :notifications

  resources :following

  resources :followers

  resources :posts

  root :to => "home#index"

end

app/models/follower.rb
class Follower < ActiveRecord::Base
  attr_accessible :avatar, :entity, :firstName, :handle, :lastName
end

app/controllers/followers_controller.rb
class FollowersController < ApplicationController
  # GET /followers
  # GET /followers.json
  def index
    @followers = Follower.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @followers }
    end
  end

  # GET /followers/1
  # GET /followers/1.json
  def show
    @follower = Follower.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @follower }
    end
  end

  # GET /followers/new
  # GET /followers/new.json
  def new
    @follower = Follower.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @follower }
    end
  end

  # GET /followers/1/edit
  def edit
    @follower = Follower.find(params[:id])
  end

  # POST /followers
  # POST /followers.json
  def create
    @follower = Follower.new(params[:follower])

    respond_to do |format|
      if @follower.save
        format.html { redirect_to @follower, notice: 'Follower was successfully created.' }
        format.json { render json: @follower, status: :created, location: @follower }
      else
        format.html { render action: "new" }
        format.json { render json: @follower.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /followers/1
  # PUT /followers/1.json
  def update
    @follower = Follower.find(params[:id])

    respond_to do |format|
      if @follower.update_attributes(params[:follower])
        format.html { redirect_to @follower, notice: 'Follower was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @follower.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /followers/1
  # DELETE /followers/1.json
  def destroy
    @follower = Follower.find(params[:id])
    @follower.destroy

    respond_to do |format|
      format.html { redirect_to followers_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/followers_helper.rb
module FollowersHelper
end

app/views/followers/_form.html.slim
= form_for @follower, :html => { :class => "form-horizontal" } do |f|
  .control-group
    = f.label :entity, :class => 'control-label'
    .controls
      = f.text_field :entity, :class => 'text_field'
  .control-group
    = f.label :handle, :class => 'control-label'
    .controls
      = f.text_field :handle, :class => 'text_field'
  .control-group
    = f.label :firstName, :class => 'control-label'
    .controls
      = f.text_field :firstName, :class => 'text_field'
  .control-group
    = f.label :lastName, :class => 'control-label'
    .controls
      = f.text_field :lastName, :class => 'text_field'
  .control-group
    = f.label :avatar, :class => 'control-label'
    .controls
      = f.text_field :avatar, :class => 'text_field'
  .form-actions
    = f.submit nil, :class => 'btn btn-primary'
    '
    = link_to t('.cancel', :default => t('helpers.links.cancel')), followers_path, :class => 'btn'

app/views/followers/edit.html.slim
- model_class = @follower.class
div class="page-header"
  h1=t '.title', :default => t('helpers.titles.edit', :model => model_class.model_name.human, :default => "Edit #{model_class.model_name.human}")
= render :partial => "form"

app/views/followers/index.html.slim
- model_class = Follower.new.class
div class="page-header"
  h1=t '.title', :default => model_class.model_name.human.pluralize
table class="table table-striped"
  thead
    tr
      th= model_class.human_attribute_name(:id)
      th= model_class.human_attribute_name(:entity)
      th= model_class.human_attribute_name(:handle)
      th= model_class.human_attribute_name(:firstName)
      th= model_class.human_attribute_name(:lastName)
      th= model_class.human_attribute_name(:avatar)
      th= model_class.human_attribute_name(:created_at)
      th=t '.actions', :default => t("helpers.actions")
  tbody
    - @followers.each do |follower|
      tr
        td= link_to follower.id, follower_path(follower)
        td= follower.entity
        td= follower.handle
        td= follower.firstName
        td= follower.lastName
        td= follower.avatar
        td=l follower.created_at
        td
          = link_to t('.edit', :default => t("helpers.links.edit")), edit_follower_path(follower), :class => 'btn btn-mini'
          '
          = link_to t('.destroy', :default => t("helpers.links.destroy")), follower_path(follower), :method => :delete, :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')), :class => 'btn btn-mini btn-danger'

= link_to t('.new', :default => t("helpers.links.new")), new_follower_path, :class => 'btn btn-primary'

app/views/followers/new.html.slim
- model_class = @follower.class
div class="page-header"
  h1=t '.title', :default => t('helpers.titles.new', :model => model_class.model_name.human, :default => "New #{model_class.model_name.human}")
= render :partial => "form"

app/views/followers/show.html.slim
- model_class = @follower.class
div class="page-header"
  h1=t '.title', :default => model_class.model_name.human

p
  strong= model_class.human_attribute_name(:entity) + ':'
  br
  = @follower.entity
p
  strong= model_class.human_attribute_name(:handle) + ':'
  br
  = @follower.handle
p
  strong= model_class.human_attribute_name(:firstName) + ':'
  br
  = @follower.firstName
p
  strong= model_class.human_attribute_name(:lastName) + ':'
  br
  = @follower.lastName
p
  strong= model_class.human_attribute_name(:avatar) + ':'
  br
  = @follower.avatar

.form-actions
  = link_to t('.back', :default => t("helpers.links.back")), followers_path, :class => 'btn'
  '
  = link_to t('.edit', :default => t("helpers.links.edit")), edit_follower_path(@follower), :class => 'btn'
  '
  = link_to t('.destroy', :default => t("helpers.links.destroy")), follower_path(@follower), :method => "delete", :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')), :class => 'btn btn-danger'